config/routes.rb
Rails.application.routes.draw do
  # if Rails.env.development?
  #   mount LetterOpenerWeb::Engine, at: '/letter_opener'
  # end
  root "static_pages#home"
  get "/about", to: "static_pages#about", as: "about"
  get "/help", to: "static_pages#help", as: "help"
  get "/contact", to: "static_pages#contact", as: "contact"
  get "client/signup", to: "clients#new"
  post "client/signup", to: "clients#create", as: "clients"
  get "client/:id", to: "clients#show", as: "client"
  get "client/:id/edit", to: "clients#edit", as: "client_edit"
  patch "client/:id", to: "clients#update", as: "client_update"
  delete "client/:id", to: "clients#destroy", as: "clients_destroy"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :account_activations, only: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  attr_accessor :remember_token, :activation_token
  before_save   :downcase_email
  before_create :create_activation_digest
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 250 },
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def Client.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def Client.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = Client.new_token
    update_attribute(:remember_digest, Client.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    ClientMailer.account_activation(self).deliver_now
  end

  private

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token  = Client.new_token
      self.activation_digest = Client.digest(activation_token)
    end

end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController

  def edit
   client = Client.find_by(email: params[:email])
   if client && !client.activated? && client.authenticated?(:activation, params[:id])
     client.activate
     log_in client
     flash[:success] = "アカウントが有効化されました"
     redirect_to client
   else
     flash[:danger] = "リンクが正しくありません"
     redirect_to root_url
   end
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :logged_in_client, only: [:edit, :update, :destroy]
  before_action :correct_client, only: [:edit, :update, :destroy]

  def new
    @client = Client.new
    @form_url = client_signup_path
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      @client.send_activation_email
      flash[:info] = "メールアドレスを確認してアカウント有効化リンクをクリックしてください"
      redirect_to root_path
    else
      render "new"
    end
  end

  def show
  end

  def edit
    @form_url = client_update_path
  end

  def update
    if @client.update_attributes(client_params)
      flash[:success] = "変更完了しました"
      redirect_to @client
    else
      render "edit"
    end
  end

  def destroy
    Client.find_by(id: params[:id]).destroy
    flash[:success] = "退会が完了しました"
    redirect_to root_path
  end


  private

    def client_params
      params.require(:client).permit(:name, :email, :password,
                                      :password_confirmation, :age,
                                       :special_notes, :gender)
    end

    def logged_in_client
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end

    def correct_client
      @client = Client.find(params[:id])
      redirect_to(root_url) unless current_client?(@client)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    client = Client.find_by(email: params[:session][:email].downcase)
    if client && client.authenticate(params[:session][:password])
      if client.activated?
        log_in client
        params[:session][:remember_me] == '1' ? remember(client) : forget(client)
        redirect_back_or client
      else
        message = "アカウントが有効化されていません。"
        message += "メールをチェックしてアカウント有効化リンクをクリックしてください"
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = "ログインできませんでした"
      render "new"
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end

  def contact
  end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = 'Coco'
    if page_title.empty?
      base_title
    else
      page_title + '||' + base_title
    end
  end

end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(client)
    session[:client_id] = client.id
  end

  def current_client
    if (client_id = session[:client_id])
      @current_user ||= Client.find_by(id: client_id)
    elsif (client_id = cookies.signed[:client_id])
      client = Client.find_by(id: client_id)
      if client && client.authenticated?(:remember, cookies[:remember_token])
        log_in client
        @current_client = client
      end
    end
  end

  def current_client?(client)
    client == current_client
  end

  def logged_in?
    !current_client.nil?
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

  def forget(client)
    client.forget
    cookies.delete(:client_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_client)
    session.delete(:client_id)
    @current_client = nil
  end

  def remember(client)
    client.remember
    # binding.pry
    cookies.permanent.signed[:client_id] = client.id
    cookies.permanent[:remember_token] = client.remember_token
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/clients/_form.html.erb
<main class="client-signup-container input-inner">
  <%= render "shared/error_messages" %>
  <%= form_with model: @client, local: true do |f| %>
    <h1>新規登録</h1>
    <table>
      <tr>
        <th><%= f.label :name, "名前" %></th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th><%= f.label :email, "メールアドレス" %></th>
        <td><%= f.email_field :email %></td>
      </tr>
      <tr>
        <th><%= f.label :password, "パスワード" %></th>
        <td><%= f.password_field :password %></td>
      </tr>
      <tr>
        <th><%= f.label :password_confirmation, "パスワード確認" %></th>
        <td><%= f.password_field :password_confirmation%></td>
      </tr>
    </table>
    <%= f.submit "新規登録", class: "btn" %>
  <% end %>
</main>

app/views/clients/edit.html.erb
<% provide(:title, "設定") %>
<div class="inner client-container">
  <aside class="side-nav">
    <nav>
      <ul>
        <li class="first-nav">
          <%= link_to client_path do %>
            <i class="fas fa-user-circle"></i>
            マイページ
          <% end %>
        </li>
        <li>
          <%= link_to "#" do%>
            <i class="fas fa-calendar-alt"></i>
            ダイアリー
          <% end %>
        </li>
        <li>
          <%= link_to "#" do%>
            <i class="far fa-sticky-note"></i>
            ノート
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="fas fa-history"></i>
            利用履歴
          <% end %>
        </li>
        <li>
          <%= link_to client_edit_path do %>
            <i class="fas fa-cog"></i>
            設定
          <% end %>
        </li>
      </ul>
    </nav>
  </aside>
  <main class="edit-container">
    <%= render "shared/error_messages" %>
    <section class="edit-form-area">
      <%= form_with model: @client, local: true do |f| %>
        <table>
          <tr class="edit-headline">
            <td colspan="2"><h1>設定を変更する</h1></td>
          </tr>
          <tr>
            <th><%= f.label :name, "名前" %></th>
            <td><%= f.text_field :name, class: "input-style" %></td>
          </tr>
          <tr>
            <th><%= f.label :email, "メールアドレス" %></th>
            <td><%= f.email_field :email, class: "input-style" %></td>
          </tr>
          <tr>
            <th><%= f.label :age, "年代" %></th>
            <td><%= f.select :age, {"10歳代": 1, "20歳代": 2, "30歳代": 3, "40歳代": 4,
              "50歳代": 5, "60歳代": 6, "それ以上": 7} %></td>
            </tr>
            <tr>
              <th><%= f.label :gender, "性別" %></th>
              <td>
                <%= f.radio_button :gender, "male", class: "radio-btn" %>
                <%= f.label :gender, "男性" %>
                <%= f.radio_button :gender, "female", class: "radio-btn" %>
                <%= f.label :gender, "女性" %>
                <%= f.radio_button :gender, "else", class: "radio-btn" %>
                <%= f.label :gender, "その他" %>
              </td>
            </tr>
            <tr>
              <th><%= f.label :password, "パスワード" %></th>
              <td><%= f.password_field :password, class: "input-style" %></td>
            </tr>
            <tr>
              <th><%= f.label :password_confirmation, "パスワード確認" %></th>
              <td><%= f.password_field :password_confirmation, class: "input-style" %></td>
            </tr>
            <tr>
              <th><%= f.label :special_notes, "特筆事項" %></th>
              <td><%= f.text_field :special_notes, class: "input-sentence-style" %></td>
            </tr>
            <tr class="btn-area">
              <td colspan="2"><%= f.submit "設定を更新する", id: "block-btn" %></td>
            </tr>
          </table>
        <% end %>
      </section>
      <section class="point-link-area">
        <table>
          <tr class="edit-headline">
            <td colspan="2"><h1>ポイント</h1></td>
          </tr>
          <tr class="total-point-area">
            <th>合計ポイント</th>
            <td>100pt</td>
          </tr>
          <tr class="btn-area">
            <td colspan="2"><%= link_to "ポイント詳細を確認", "#", id: "block-btn" %></td>
          </tr>
        </table>
      </section>
      <section class="else-link-area">
        <table>
          <tr class="edit-headline">
            <td colspan="2"><h1>その他</h1></td>
          </tr>
          <tr class="btn-area">
            <td colspan="2"><%= link_to "Lineで通知を受け取る", "#", id: "block-btn" %></td>
          </tr>
          <tr class="btn-area">
            <td colspan="2"><%= link_to "メールアドレス変更", client_edit_path(current_client), id: "block-btn" %></td>
          </tr>
          <tr class="btn-area">
            <td colspan="2"><%= link_to "退会受付画面", clients_destroy_path(@client), method: :delete,
                                  data: { confirm: "本当に退会しますか？" }, id: "block-btn" %></td>
          </tr>
        </table>
      </section>
  </main>
</div>

app/views/clients/new.html.erb
<main class="client-signup-container input-inner">
  <%= render "shared/error_messages" %>
  <%= form_with model: @client, local: true do |f| %>
    <h1>新規登録</h1>
    <table>
      <tr>
        <th><%= f.label :name, "名前" %></th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th><%= f.label :email, "メールアドレス" %></th>
        <td><%= f.email_field :email %></td>
      </tr>
      <tr>
        <th><%= f.label :password, "パスワード" %></th>
        <td><%= f.password_field :password %></td>
      </tr>
      <tr>
        <th><%= f.label :password_confirmation, "パスワード確認" %></th>
        <td><%= f.password_field :password_confirmation%></td>
      </tr>
    </table>
    <%= f.submit "新規登録", class: "btn" %>
  <% end %>
</main>

app/views/clients/show.html.erb
<h1>Client#show</h1>
<p>Find me in app/views/client/show.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
  <div class="inner footer-inner">
    <nav>
      <p>カウンセラーを探す</p>
      <ul>
        <li><%= link_to "人気順で探す", "#" %></li>
        <li><%= link_to "経歴順で探す", "#" %></li>
        <li><%= link_to "相談内容から探す", "#" %></li>
      </ul>
    </nav>
    <nav>
      <p>お問い合わせ</p>
      <ul>
        <li><%= link_to "よくある質問", "#" %></li>
        <li><%= link_to "お問い合わせ", contact_path %></li>
      </ul>
    </nav>
    <nav>
      <p>Cocoとは</p>
      <ul>
        <li><%= link_to "会社概要", "#" %></li>
        <li><%= link_to "サービスについて", about_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="inner header-inner">
    <h1>
      <%= link_to "COCORO", root_path %>
    </h1>
    <nav>
      <ul>
        <li>
          <%= link_to "#" do%>
            カウンセラーを探す
            <i class="fas fa-caret-right nav-icon"></i>
          <% end %>
        </li>
        <li>
          <%= link_to about_path do%>
            Cocoとは
            <i class="fas fa-caret-right nav-icon"></i>
          <% end %>
        </li>
        <% if logged_in? %>
          <li>
            <%= link_to current_client do%>
              Myアカウント
              <i class="fas fa-caret-right nav-icon"></i>
            <% end %>
          </li>
          <li>
            <%= link_to logout_path, method: :delete do %>
              ログアウト
              <i class="fas fa-caret-right nav-icon"></i>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to client_signup_path do %>
              新規登録
              <i class="fas fa-caret-right nav-icon"></i>
            <% end %>
          </li>
          <li>
            <%= link_to login_path do %>
              ログイン
              <i class="fas fa-caret-right nav-icon"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
       <div class="alert alert-<%= message_type %>"><%= message %></div>
     <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @client.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@client.errors.count, "error") %>.
    </div>
    <ul>
    <% @client.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'サービス詳細') %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "お問い合せ") %>

app/views/static_pages/help.html.erb
<% provide(:title, 'ヘルプ') %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "トップページ") %>
<section class="main-img">
  <h1>心理資格を持つカウンセラーに気軽に相談できるオンラインカウンセリングサービス</h1>
  <%= link_to "カウンセリングを始める" ,"#" %>
</section>
<section class="main-counselor-serch-area">
    <h1>日本中のカウンセラーから自分に合ったカウンセラーを選べます</h1>
  <div class="counselor-list inner">
    <ul>
      <li>
        <%= link_to("#") do%>
          <div class="counselor-info">
            <%= image_tag("yamada.jpg") %>
            <p>
              <span class="name">山田太郎</span>
              <span class="license">臨床心理士</span>
            </p>
          </div>
          <div class="counselor-introduction">
            <p>誠心誠意頑張ります。</p>
          </div>
        <% end %>
      </li>
      <li>
        <%= link_to("#") do%>
          <div class="counselor-info">
            <%= image_tag("yamada.jpg") %>
            <p>
              <span class="name">山田太郎</span>
              <span class="license">臨床心理士</span>
            </p>
          </div>
          <div class="counselor-introduction">
            <p>誠心誠意頑張ります。</p>
          </div>
        <% end %>
      </li>
      <li>
        <%= link_to("#") do%>
          <div class="counselor-info">
            <%= image_tag("yamada.jpg") %>
            <p>
              <span class="name">山田太郎</span>
              <span class="license">臨床心理士</span>
            </p>
          </div>
          <div class="counselor-introduction">
            <p>誠心誠意頑張ります。</p>
          </div>
        <% end %>
      </li>
      <li>
        <%= link_to("#") do%>
          <div class="counselor-info">
            <%= image_tag("yamada.jpg") %>
            <p>
              <span class="name">山田太郎</span>
              <span class="license">臨床心理士</span>
            </p>
          </div>
          <div class="counselor-introduction">
            <p>誠心誠意頑張ります。</p>
          </div>
        <% end %>
      </li>
      <li>
        <%= link_to("#") do%>
          <div class="counselor-info">
            <%= image_tag("yamada.jpg") %>
            <p>
              <span class="name">山田太郎</span>
              <span class="license">臨床心理士</span>
            </p>
          </div>
          <div class="counselor-introduction">
            <p>誠心誠意頑張ります。</p>
          </div>
        <% end %>
      </li>
      <li>
        <%= link_to("#") do%>
          <div class="counselor-info">
            <%= image_tag("yamada.jpg") %>
            <p>
              <span class="name">山田太郎</span>
              <span class="license">臨床心理士</span>
            </p>
          </div>
          <div class="counselor-introduction">
            <p>誠心誠意頑張ります。</p>
          </div>
        <% end %>
      </li>
      <li>
        <%= link_to("#") do%>
          <div class="counselor-info">
            <%= image_tag("yamada.jpg") %>
            <p>
              <span class="name">山田太郎</span>
              <span class="license">臨床心理士</span>
            </p>
          </div>
          <div class="counselor-introduction">
            <p>誠心誠意頑張ります。</p>
          </div>
        <% end %>
      </li>
      <li>
        <%= link_to("#") do%>
          <div class="counselor-info">
            <%= image_tag("yamada.jpg") %>
            <p>
              <span class="name">山田太郎</span>
              <span class="license">臨床心理士</span>
            </p>
          </div>
          <div class="counselor-introduction">
            <p>誠心誠意頑張ります。</p>
          </div>
        <% end %>
      </li>
      <li>
        <%= link_to("#") do%>
          <div class="counselor-info">
            <%= image_tag("yamada.jpg") %>
            <p>
              <span class="name">山田太郎</span>
              <span class="license">臨床心理士</span>
            </p>
          </div>
          <div class="counselor-introduction">
            <p>誠心誠意頑張ります。</p>
          </div>
        <% end %>
      </li>
    </ul>
    <%= link_to "カウンセラーを探す", "#", class: "counselor-serch-btn" %>
  </div>
</section>
<section class="main-client-question-area">
  <div class="inner">
    <h1>よくある質問</h1>
    <ul>
      <li><%= link_to "料金体系について", "#" %></li>
      <li><%= link_to "料金体系について", "#" %></li>
      <li><%= link_to "料金体系について", "#" %></li>
      <li><%= link_to "料金体系について", "#" %></li>
      <li><%= link_to "料金体系について", "#" %></li>
      <li><%= link_to "料金体系について", "#" %></li>
    </ul>
  </div>
  <%= link_to "もっと詳しく" , "#" , class: "question-btn"%>
</section>
<section class="main-couselor-gide-area">
<h1 class="gide-heading">カウンセラーの方へ</h1>
<p>事務所を持たずに場所や時間にとらわれず自由な働き方を実現できます</p>
  <div class="inner">
    <h1 class="gide-heading">カウンセラー登録をして働く方法</h1>
    <ol>
      <li>
        <h1>First Step</h1>
        <h2>カウンセラーアカウント作成</h2>
        <%= image_tag("input.jpg")%>
        <p>氏名や住所など基本情報及びカウンセラー免許、運転免許証を登録してもらいます</p>
      </li>
      <li>
        <h1>Secound Step</h1>
        <h2>審査</h2>
        <%= image_tag("examination.jpg")%>
        <p>カウンセラー免許証と運転免許証を照らし合わせ審査を行います</p>
      </li>
      <li>
        <h1>Thired Step</h1>
        <h2>登録完了</h2>
        <%= image_tag("pass.jpg")%>
        <p>審査を通過後すぐに予約の受付が可能となります</p>
      </li>
    </ol>
  </div>
  <%= link_to "カウンセラー登録", "#", class: "couselor-singnup-btn" %>
</section>
<section class="main-counselor-question-area">
  <div class="inner">
    <h1>よくある質問</h1>
    <ul>
      <li><%= link_to "料金体系について", "#" %></li>
      <li><%= link_to "料金体系について", "#" %></li>
      <li><%= link_to "料金体系について", "#" %></li>
      <li><%= link_to "料金体系について", "#" %></li>
      <li><%= link_to "料金体系について", "#" %></li>
      <li><%= link_to "料金体系について", "#" %></li>
    </ul>
  </div>
  <%= link_to "もっと詳しく" , "#" , class: "question-btn"%>
</section>